# This is my second Note Book - NumPy Starter

In [ ]:
#makesure to install numpy package first with pip install numpy
 
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

print("Index:", arr[4])

print("Mask:", arr > 3)

print("Filtered array:", arr[arr > 3])

Original array: [1 2 3 4 5]
Index: 5
Mask: [False False False  True  True]
Filtered array: [4 5]


In [ ]:
#Play around with numpy arrays and indexing
import numpy as np
import math

grid = np.random.randint(1, 1_000, size=(5, 5))
print("Random grid:\n", grid)


#Array Operations
a = np.array([1, 2, 3, 4])
print(a * 2)  # Vectorized multiplication
print(a + 10) # broadcasting addition
print(np.sqrt(a))  # unoversal function

#without numpy
b = [1, 2, 3, 4]
print([num*2 for num in b ])
print([num+10 for num in b ])
print([math.sqrt(num) for num in b ])


Random grid:
 [[787  14 903 406 594]
 [519 217 674 775 696]
 [752 754 352  98 107]
 [602 471 533 677 236]
 [612 528  61 674  19]]
[2 4 6 8]
[11 12 13 14]
[1.         1.41421356 1.73205081 2.        ]
[2, 4, 6, 8]
[11, 12, 13, 14]
[1.0, 1.4142135623730951, 1.7320508075688772, 2.0]
