# This is my second Note Book - NumPy Starter

In [ ]:
#makesure to install numpy package first with pip install numpy
 
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

print("Index:", arr[4])

print("Mask:", arr > 3)

print("Filtered array:", arr[arr > 3])

Original array: [1 2 3 4 5]
Index: 5
Mask: [False False False  True  True]
Filtered array: [4 5]


In [ ]:
#Play around with numpy arrays and indexing
import numpy as np
import math

grid = np.random.randint(1, 1_000, size=(5, 5))
print("Random grid:\n", grid)


#Array Operations
a = np.array([1, 2, 3, 4])
print(a * 2)  # Vectorized multiplication
print(a + 10) # broadcasting addition
print(np.sqrt(a))  # unoversal function

#without numpy
b = [1, 2, 3, 4]
print([num*2 for num in b ])
print([num+10 for num in b ])
print([math.sqrt(num) for num in b ])


Random grid:
 [[787  14 903 406 594]
 [519 217 674 775 696]
 [752 754 352  98 107]
 [602 471 533 677 236]
 [612 528  61 674  19]]
[2 4 6 8]
[11 12 13 14]
[1.         1.41421356 1.73205081 2.        ]
[2, 4, 6, 8]
[11, 12, 13, 14]
[1.0, 1.4142135623730951, 1.7320508075688772, 2.0]


In [6]:
import numpy as np
import time
import math

# Create big data
N = 10_000_001
my_list = list(range(N))
arr = np.arange(N)

# Python loop version
t0 = time.perf_counter()
roots_list = [math.sqrt(num) for num in my_list]
t1 = time.perf_counter()

# NumPy version (vectorised)
roots_arr = np.sqrt(arr)
t2 = time.perf_counter()

print(f"Python list loop: {t1 - t0:.4f} seconds")
print(f"NumPy array vectorised loop: {t2 - t1:.4f} seconds")

Python list loop: 1.6521 seconds
NumPy array vectorised loop: 0.0346 seconds


NumPy Builtin Functions

In [ ]:
import numpy as np

#arange function
arr = np.arange(10)
print("Array with arange 10: ",arr)
arr = np.arange(1,10)
print("Array with arange 1 to 10: ",arr)
arr = np.arange(1,10,2)
print("Array with arange 1 to 10 with step 2: ",arr)
arr = np.arange(1,10,0.5)
print("Array with arange 1 to 10 with step 0.5: ",arr)

#zeros function
arr1z = np.zeros(shape=4) 
print("Array of 4 with Zero: ",arr1z)
arr2z = np.zeros(5) 
print("Array of 4 with Zero without shape kw: ",arr2z)
arr2d = np.zeros(shape=(2,5))
print("2D Array 2,5 with Zero: ",arr2d)
arr3d = np.zeros(shape=(2,2,5)) 
print("3D Array 2,2,5 with Zero: ",arr3d)

#onse function
arr = np.ones(shape=4)
print("Array of 4: ",arr)
arr2d = np.ones(shape=(2,5)) 
print("2D Array 2,5: ",arr2d)
arr3d = np.ones(shape=(2,2,5))
print("3D Array 2,2,5: ",arr3d)

#linspace function
arr = np.linspace(1,10,5)
print("Array with linspace 1 to 10 with 5 elements: ",arr)
arr = np.linspace(1,10,4)
print("Array with linspace 1 to 10 with 4 elements: ",arr)
arr = np.linspace(1,10,3)
print("Array with linspace 1 to 10 with 3 elements: ",arr)

#logspace function
arr = np.logspace(1,10,5)
print("Array with logspace 1 to 10 with 5 elements: ",arr)

Array with arange 10:  [0 1 2 3 4 5 6 7 8 9]
Array with arange 1 to 10:  [1 2 3 4 5 6 7 8 9]
Array with arange 1 to 10 with step 2:  [1 3 5 7 9]
Array with arange 1 to 10 with step 0.5:  [1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
Array of 4 with Zero:  [0. 0. 0. 0.]
Array of 4 with Zero without shape kw:  [0. 0. 0. 0. 0.]
2D Array 2,5 with Zero:  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
3D Array 2,2,5 with Zero:  [[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
Array of 4:  [1. 1. 1. 1.]
2D Array 2,5:  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
3D Array 2,2,5:  [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [ ]:
#NumPy Advanced Topics